### ISSUE TITLE
Error with Wan2.1-Fun-1.3B-Control inference script - 'WanModel' object has no attribute 'ref_conv'

### ISSUE THREAD

**Issue by fusheng-ji** [modelscope/DiffSynth-Studio#890]
Hi @Artiprocher , 

Thanks for your awesome project. 

I am trying to infer video generation based on control video and reference image inputs with [Wan2.1-Fun-1.3B-Control](https://github.com/modelscope/DiffSynth-Studio/blob/main/examples/wanvideo/model_inference/Wan2.1-Fun-V1.1-1.3B-Control.py). 

However, I met the error in diffsynth/pipelines/wan_video_new.py: AttributeError: 'WanModel' object has no attribute 'ref_conv'

I have checked the [hash_state_dict_keys](https://github.com/modelscope/DiffSynth-Studio/blob/8c13362dcff157162e4816cd80968dcc52c94452/diffsynth/models/wan_video_dit.py#L569) of Wan2.1-Fun-1.3B-Control, which lacks "has_ref_conv", but the diffsynth/pipelines/wan_video_new.py call [dit.ref_conv](https://github.com/modelscope/DiffSynth-Studio/blob/8c13362dcff157162e4816cd80968dcc52c94452/diffsynth/pipelines/wan_video_new.py#L1229) to process reference_latents as default. 

In that way, the control pipeline can work fine with  Wan2.1-Fun-V1.1-1.3B-Control instead of the Wan2.1-Fun-1.3B-Control model.

Could you help me figure out how to fix this error? 

Many thanks!

**Comment by Artiprocher** [comment]
@fusheng-ji Wan2.1-Fun-1.3B-Control doesn't support reference image.

**Comment by doubleZ0108** [comment]
@fusheng-ji Maybe you used the wrong model as `Wan2.1-Fun-1.3B-Control-Camera`, which is different from `Wan2.1-Fun-1.3B-Control`, have a check.
